export const wikipedias = {
    en: {
        code: "en",
        language: "English",
        script: "English",
        name: "English Wikipedia",
    },
    de: {
        code: "de",
        language: "German",
        script: "Latn",
        name: "German Wikipedia",
    },
    fr: {
        code: "fr",
        language: "French",
        script: "Latn",
        name: "French Wikipedia",
    },
    nl: {
        code: "nl",
        language: "Dutch",
        script: "Latn",
        name: "Dutch Wikipedia",
    },
    it: {
        code: "it",
        language: "Italian",
        script: "Latn",
        name: "Italian Wikipedia",
    },
    es: {
        code: "es",
        language: "Spanish",
        script: "Latn",
        name: "Spanish Wikipedia",
    },
    ru: {
        code: "ru",
        language: "Russian",
        script: "Cyrl",
        name: "Russian Wikipedia",
    },
    sv: {
        code: "sv",
        language: "Swedish",
        script: "Latn",
        name: "Swedish Wikipedia",
    },
    pl: {
        code: "pl",
        language: "Polish",
        script: "Latn",
        name: "Polish Wikipedia",
    },
    ja: {
        code: "ja",
        language: "Japanese",
        script: "Jpan",
        name: "Japanese Wikipedia",
    },
    pt: {
        code: "pt",
        language: "Portuguese",
        script: "English",
        name: "Portuguese Wikipedia",
    },
    ar: {
        code: "ar",
        language: "Arabic",
        script: "Arab",
        name: "Arabic Wikipedia",
    },
    zh: {
        code: "zh",
        language: "Chinese",
        script: "Hans/Hant",
        name: "Chinese Wikipedia",
    },
    uk: {
        code: "uk",
        language: "Ukrainian",
        script: "Cyrl",
        name: "Ukrainian Wikipedia",
    },
    ca: {
        code: "ca",
        language: "Catalan",
        script: "Latn",
        name: "Catalan Wikipedia",
    },
    no: {
        code: "no",
        language: "Norwegian (Bokmål)",
        script: "Latn",
        name: "Bokmål/Riksmål Wikipedia",
    },
    fi: {
        code: "fi",
        language: "Finnish",
        script: "Latn",
        name: "Finnish Wikipedia",
    },
    cs: {
        code: "cs",
        language: "Czech",
        script: "Latn",
        name: "Czech Wikipedia",
    },
    hu: {
        code: "hu",
        language: "Hungarian",
        script: "Latn",
        name: "Hungarian Wikipedia",
    },
    tr: {
        code: "tr",
        language: "Turkish",
        script: "Latn",
        name: "Turkish Wikipedia",
    },
    ro: {
        code: "ro",
        language: "Romanian",
        script: "Latn",
        name: "Romanian Wikipedia",
    },
    sw: {
        code: "sw",
        language: "Swahili",
        script: "English",
        name: "Swahili Wikipedia",
    },
    ko: {
        code: "ko",
        language: "Korean",
        script: "Hang",
        name: "Korean Wikipedia",
    },
    kk: {
        code: "kk",
        language: "Kazakh",
        script: "Cyrl / Latin / Arab",
        name: "Kazakh Wikipedia",
    },
    vi: {
        code: "vi",
        language: "Vietnamese",
        script: "Latn",
        name: "Vietnamese Wikipedia",
    },
    da: {
        code: "da",
        language: "Danish",
        script: "Latn",
        name: "Danish Wikipedia",
    },
    eo: {
        code: "eo",
        language: "Esperanto",
        script: "Latn",
        name: "Esperanto Wikipedia",
    },
    sr: {
        code: "sr",
        language: "Serbian",
        script: "Cyrl/Latn",
        name: "Serbian Wikipedia",
    },
    id: {
        code: "id",
        language: "Indonesian",
        script: "Latn",
        name: "Indonesian Wikipedia",
    },
    lt: {
        code: "lt",
        language: "Lithuanian",
        script: "Latn",
        name: "Lithuanian Wikipedia",
    },
    vo: {
        code: "vo",
        language: "Volapük",
        script: "Latn",
        name: "Volapük Wikipedia",
    },
    sk: {
        code: "sk",
        language: "Slovak",
        script: "Latn",
        name: "Slovak Wikipedia",
    },
    he: {
        code: "he",
        language: "Hebrew",
        script: "Hebr",
        name: "Hebrew Wikipedia",
    },
    fa: {
        code: "fa",
        language: "Persian",
        script: "Perso",
        name: "Persian Wikipedia",
    },
    bg: {
        code: "bg",
        language: "Bulgarian",
        script: "Cyrl",
        name: "Bulgarian Wikipedia",
    },
    sl: {
        code: "sl",
        language: "Slovene",
        script: "Latn",
        name: "Slovene Wikipedia",
    },
    eu: {
        code: "eu",
        language: "Basque",
        script: "Latn",
        name: "Basque Wikipedia",
    },
    war: {
        code: "war",
        language: "Waray-Waray",
        script: "Latn",
        name: "Waray-Waray Wikipedia",
    },
    lmo: {
        code: "lmo",
        language: "Lombard",
        script: "Latn",
        name: "Lombard Wikipedia",
    },
    et: {
        code: "et",
        language: "Estonian",
        script: "Latn",
        name: "Estonian Wikipedia",
    },
    hr: {
        code: "hr",
        language: "Croatian",
        script: "Latn",
        name: "Croatian Wikipedia",
    },
    new: {
        code: "new",
        language: "Newar / Nepal Bhasa",
        script: "Deva",
        name: "Newar Wikipedia",
    },
    te: {
        code: "te",
        language: "Telugu",
        script: "Telu",
        name: "Telugu Wikipedia",
    },
    nn: {
        code: "nn",
        language: "Norwegian (Nynorsk)",
        script: "Latn",
        name: "Nynorsk Wikipedia",
    },
    th: {
        code: "th",
        language: "Thai",
        script: "Thai",
        name: "Thai Wikipedia",
    },
    gl: {
        code: "gl",
        language: "Galician",
        script: "Latn",
        name: "Galician Wikipedia",
    },
    el: {
        code: "el",
        language: "Greek",
        script: "Grek",
        name: "Greek Wikipedia",
    },
    ceb: {
        code: "ceb",
        language: "Cebuano",
        script: "Latn",
        name: "Cebuano Wikipedia",
    },
    simple: {
        code: "simple",
        language: "Simple English",
        script: "Latn",
        name: "Simple English Wikipedia",
    },
    ms: {
        code: "ms",
        language: "Malay",
        script: "Latn",
        name: "Malay Wikipedia",
    },
    ht: {
        code: "ht",
        language: "Haitian",
        script: "Latn",
        name: "Haitian Creole Wikipedia",
    },
    bs: {
        code: "bs",
        language: "Bosnian",
        script: "Latn",
        name: "Bosnian Wikipedia",
    },
    bpy: {
        code: "bpy",
        language: "Bishnupriya Manipuri",
        script: "Beng",
        name: "Bishnupriya Manipuri Wikipedia",
    },
    lb: {
        code: "lb",
        language: "Luxembourgish",
        script: "Latn",
        name: "Luxembourgish Wikipedia",
    },
    ka: {
        code: "ka",
        language: "Georgian",
        script: "Geor",
        name: "Georgian Wikipedia",
    },
    is: {
        code: "is",
        language: "Icelandic",
        script: "Latn",
        name: "Icelandic Wikipedia",
    },
    sq: {
        code: "sq",
        language: "Albanian",
        script: "Latn",
        name: "Albanian Wikipedia",
    },
    la: {
        code: "la",
        language: "Latin",
        script: "Latn",
        name: "Latin Wikipedia",
    },
    br: {
        code: "br",
        language: "Breton",
        script: "Latn",
        name: "Breton Wikipedia",
    },
    hi: {
        code: "hi",
        language: "Hindi",
        script: "Deva",
        name: "Hindi Wikipedia",
    },
    az: {
        code: "az",
        language: "Azerbaijani",
        script: "Latn/Arab",
        name: "Azerbaijani Wikipedia",
    },
    bn: {
        code: "bn",
        language: "Bengali",
        script: "Beng",
        name: "Bengali Wikipedia",
    },
    mk: {
        code: "mk",
        language: "Macedonian",
        script: "Cyrl",
        name: "Macedonian Wikipedia",
    },
    mr: {
        code: "mr",
        language: "Marathi",
        script: "Deva",
        name: "Marathi Wikipedia",
    },
    sh: {
        code: "sh",
        language: "Serbo-Croatian",
        script: "Latn/Cyrl",
        name: "Serbo-Croatian Wikipedia",
    },
    tl: {
        code: "tl",
        language: "Tagalog",
        script: "Latn",
        name: "Tagalog Wikipedia",
    },
    cy: {
        code: "cy",
        language: "Welsh",
        script: "Latn",
        name: "Welsh Wikipedia",
    },
    io: {
        code: "io",
        language: "Ido",
        script: "Latn",
        name: "Ido Wikipedia",
    },
    pms: {
        code: "pms",
        language: "Piedmontese",
        script: "Latn",
        name: "Piedmontese Wikipedia",
    },
    lv: {
        code: "lv",
        language: "Latvian",
        script: "Latn",
        name: "Latvian Wikipedia",
    },
    ta: {
        code: "ta",
        language: "Tamil",
        script: "Taml",
        name: "Tamil Wikipedia",
    },
    su: {
        code: "su",
        language: "Sundanese",
        script: "Latn",
        name: "Sundanese Wikipedia",
    },
    oc: {
        code: "oc",
        language: "Occitan",
        script: "Latn",
        name: "Occitan Wikipedia",
    },
    jv: {
        code: "jv",
        language: "Javanese",
        script: "Latn",
        name: "Javanese Wikipedia",
    },
    nap: {
        code: "nap",
        language: "Neapolitan",
        script: "Latn",
        name: "Neapolitan Wikipedia",
    },
    nds: {
        code: "nds",
        language: "Low Saxon",
        script: "Latn",
        name: "Low Saxon Wikipedia",
    },
    scn: {
        code: "scn",
        language: "Sicilian",
        script: "Latn",
        name: "Sicilian Wikipedia",
    },
    be: {
        code: "be",
        language: "Belarusian",
        script: "Cyrl",
        name: "Belarusian Wikipedia",
    },
    ast: {
        code: "ast",
        language: "Asturian",
        script: "Latn",
        name: "Asturian Wikipedia",
    },
    ku: {
        code: "ku",
        language: "Kurdish",
        script: "Latn/Arab",
        name: "Kurdish Wikipedia",
    },
    wa: {
        code: "wa",
        language: "Walloon",
        script: "Latn",
        name: "Walloon Wikipedia",
    },
    af: {
        code: "af",
        language: "Afrikaans",
        script: "Latn",
        name: "Afrikaans Wikipedia",
    },
    "be-x-old": {
        code: "be-x-old",
        language: "Belarusian (Taraškievica)",
        script: "Cyrl",
        name: "Belarusian (Taraškievica) Wikipedia",
    },
    an: {
        code: "an",
        language: "Aragonese",
        script: "Latn",
        name: "Aragonese Wikipedia",
    },
    ksh: {
        code: "ksh",
        language: "Ripuarian",
        script: "Latn",
        name: "Ripuarian Wikipedia",
    },
    szl: {
        code: "szl",
        language: "Silesian",
        script: "Latn",
        name: "Silesian Wikipedia",
    },
    fy: {
        code: "fy",
        language: "West Frisian",
        script: "Latn",
        name: "West Frisian Wikipedia",
    },
    frr: {
        code: "frr",
        language: "North Frisian",
        script: "Latn",
        name: "North Frisian Wikipedia",
    },
    yue: {
        code: "yue",
        language: "Cantonese",
        script: "Hant",
        name: "Cantonese Wikipedia",
    },
    ur: {
        code: "ur",
        language: "Urdu",
        script: "Arab",
        name: "Urdu Wikipedia",
    },
    ia: {
        code: "ia",
        language: "Interlingua",
        script: "Latn/Arab",
        name: "Interlingua Wikipedia",
    },
    ga: {
        code: "ga",
        language: "Irish",
        script: "Latn",
        name: "Irish Wikipedia",
    },
    yi: {
        code: "yi",
        language: "Yiddish",
        script: "Hebr",
        name: "Yiddish Wikipedia",
    },
    als: {
        code: "als",
        language: "Alemannic",
        script: "Latn",
        name: "Alemannic Wikipedia",
    },
    hy: {
        code: "hy",
        language: "Armenian",
        script: "Armn",
        name: "Armenian Wikipedia",
    },
    am: {
        code: "am",
        language: "Amharic",
        script: "Geez",
        name: "Amharic Wikipedia",
    },
    "roa-rup": {
        code: "roa-rup",
        language: "Aromanian",
        script: "Latn",
        name: "Aromanian Wikipedia",
    },
    "map-bms": {
        code: "map-bms",
        language: "Banyumasan",
        script: "Latn",
        name: "Banyumasan Wikipedia",
    },
    bh: {
        code: "bh",
        language: "Bihari",
        script: "Deva",
        name: "Bihari Wikipedia",
    },
    co: {
        code: "co",
        language: "Corsican",
        script: "Latn",
        name: "Corsican Wikipedia",
    },
    cv: {
        code: "cv",
        language: "Chuvash",
        script: "Latn",
        name: "Chuvash Wikipedia",
    },
    dv: {
        code: "dv",
        language: "Divehi",
        script: "Thaa",
        name: "Divehi Wikipedia",
    },
    "nds-nl": {
        code: "nds-nl",
        language: "Dutch Low Saxon",
        script: "Latn",
        name: "Dutch Low Saxon Wikipedia",
    },
    fo: {
        code: "fo",
        language: "Faroese",
        script: "Latn",
        name: "Faroese Wikipedia",
    },
    fur: {
        code: "fur",
        language: "Friulian",
        script: "Latn",
        name: "Friulian Wikipedia",
    },
    glk: {
        code: "glk",
        language: "Gilaki",
        script: "Perso",
        name: "Gilaki Wikipedia",
    },
    gu: {
        code: "gu",
        language: "Gujarati",
        script: "Gujr",
        name: "Gujarati Wikipedia",
    },
    ilo: {
        code: "ilo",
        language: "Ilokano",
        script: "Latn",
        name: "Ilokano Wikipedia",
    },
    kn: {
        code: "kn",
        language: "Kannada",
        script: "Knda",
        name: "Kannada Wikipedia",
    },
    pam: {
        code: "pam",
        language: "Kapampangan",
        script: "Latn",
        name: "Kapampangan Wikipedia",
    },
    csb: {
        code: "csb",
        language: "Kashubian",
        script: "Latn",
        name: "Kashubian Wikipedia",
    },
    km: {
        code: "km",
        language: "Khmer",
        script: "Khmr",
        name: "Khmer Wikipedia",
    },
    lij: {
        code: "lij",
        language: "Ligurian",
        script: "Latn",
        name: "Ligurian Wikipedia",
    },
    li: {
        code: "li",
        language: "Limburgish",
        script: "Latn",
        name: "Limburgish Wikipedia",
    },
    ml: {
        code: "ml",
        language: "Malayalam",
        script: "Mlym",
        name: "Malayalam Wikipedia",
    },
    gv: {
        code: "gv",
        language: "Manx",
        script: "Latn",
        name: "Manx Wikipedia",
    },
    mi: {
        code: "mi",
        language: "Māori",
        script: "Latn",
        name: "Māori Wikipedia",
    },
    mt: {
        code: "mt",
        language: "Maltese",
        script: "Latn",
        name: "Maltese Wikipedia",
    },
    nah: {
        code: "nah",
        language: "Nāhuatl",
        script: "Latn",
        name: "Nāhuatl Wikipedia",
    },
    ne: {
        code: "ne",
        language: "Nepali",
        script: "Deva",
        name: "Nepali Wikipedia",
    },
    nrm: {
        code: "nrm",
        language: "Norman",
        script: "Latn",
        name: "Norman Wikipedia",
    },
    se: {
        code: "se",
        language: "Northern Sami",
        script: "Latn",
        name: "Northern Sami Wikipedia",
    },
    nov: {
        code: "nov",
        language: "Novial",
        script: "Latn",
        name: "Novial Wikipedia",
    },
    qu: {
        code: "qu",
        language: "Quechua",
        script: "Latn",
        name: "Quechua Wikipedia",
    },
    os: {
        code: "os",
        language: "Ossetian",
        script: "Cyrl",
        name: "Ossetian Wikipedia",
    },
    pi: {
        code: "pi",
        language: "Pali",
        script: "Deva",
        name: "Pali Wikipedia",
    },
    pag: {
        code: "pag",
        language: "Pangasinan",
        script: "Latn",
        name: "Pangasinan Wikipedia",
    },
    ps: {
        code: "ps",
        language: "Pashto",
        script: "Arab",
        name: "Pashto Wikipedia",
    },
    pdc: {
        code: "pdc",
        language: "Pennsylvania German",
        script: "Latn",
        name: "Pennsylvania German Wikipedia",
    },
    rm: {
        code: "rm",
        language: "Romansh",
        script: "Latn",
        name: "Romansh Wikipedia[c]",
    },
    "bat-smg": {
        code: "bat-smg",
        language: "Samogitian",
        script: "Latn",
        name: "Samogitian Wikipedia",
    },
    sa: {
        code: "sa",
        language: "Sanskrit",
        script: "Deva",
        name: "Sanskrit Wikipedia",
    },
    gd: {
        code: "gd",
        language: "Scottish Gaelic",
        script: "Latn",
        name: "Scottish Gaelic Wikipedia",
    },
    sco: {
        code: "sco",
        language: "Scots",
        script: "Latn",
        name: "Scots Wikipedia",
    },
    sc: {
        code: "sc",
        language: "Sardinian",
        script: "Latn",
        name: "Sardinian Wikipedia",
    },
    si: {
        code: "si",
        language: "Sinhalese",
        script: "Sinh",
        name: "Sinhalese Wikipedia",
    },
    tg: {
        code: "tg",
        language: "Tajik",
        script: "Cyrl",
        name: "Tajik Wikipedia",
    },
    "roa-tara": {
        code: "roa-tara",
        language: "Tarantino",
        script: "Latn",
        name: "Tarantino Wikipedia",
    },
    tt: {
        code: "tt",
        language: "Tatar",
        script: "Cyrl/Latn",
        name: "Tatar Wikipedia",
    },
    to: {
        code: "to",
        language: "Tongan",
        script: "Latn",
        name: "Tongan Wikipedia",
    },
    tk: {
        code: "tk",
        language: "Turkmen",
        script: "Latn",
        name: "Turkmen Wikipedia",
    },
    hsb: {
        code: "hsb",
        language: "Upper Sorbian",
        script: "Latn",
        name: "Upper Sorbian Wikipedia",
    },
    uz: {
        code: "uz",
        language: "Uzbek",
        script: "Latn/Cyrl",
        name: "Uzbek Wikipedia",
    },
    vec: {
        code: "vec",
        language: "Venetian",
        script: "Latn",
        name: "Venetian Wikipedia",
    },
    "fiu-vro": {
        code: "fiu-vro",
        language: "Võro",
        script: "Latn",
        name: "Voro Wikipedia",
    },
    wuu: {
        code: "wuu",
        language: "Wu",
        script: "Hans",
        name: "Wu Wikipedia",
    },
    vls: {
        code: "vls",
        language: "West Flemish",
        script: "Latn",
        name: "West Flemish Wikipedia",
    },
    yo: {
        code: "yo",
        language: "Yoruba",
        script: "Latn",
        name: "Yoruba Wikipedia",
    },
    diq: {
        code: "diq",
        language: "Zazaki",
        script: "Latn",
        name: "Zazaki Wikipedia",
    },
    "zh-min-nan": {
        code: "zh-min-nan",
        language: "Min Nan",
        script: "Latn",
        name: "Min Nan Wikipedia",
    },
    "zh-classical": {
        code: "zh-classical",
        language: "Classical Chinese",
        script: "Hant",
        name: "Classical Chinese Wikipedia",
    },
    frp: {
        code: "frp",
        language: "Franco-Provençal/Arpitan",
        script: "Latn",
        name: "Franco-Provençal Wikipedia",
    },
    lad: {
        code: "lad",
        language: "Ladino",
        script: "Latn",
        name: "Ladino Wikipedia",
    },
    bar: {
        code: "bar",
        language: "Bavarian",
        script: "Latn",
        name: "Bavarian Wikipedia",
    },
    bcl: {
        code: "bcl",
        language: "Central_Bicolano",
        script: "Latn",
        name: "Central Bicolano Wikipedia",
    },
    kw: {
        code: "kw",
        language: "Cornish",
        script: "Latn",
        name: "Cornish Wikipedia",
    },
    mn: {
        code: "mn",
        language: "Mongolian",
        script: "Cyrl",
        name: "Mongolian Wikipedia",
    },
    haw: {
        code: "haw",
        language: "Hawaiian",
        script: "Latn",
        name: "Hawaiian Wikipedia",
    },
    ang: {
        code: "ang",
        language: "Anglo-Saxon",
        script: "Latn",
        name: "Anglo-Saxon Wikipedia",
    },
    ln: {
        code: "ln",
        language: "Lingala",
        script: "Latn",
        name: "Lingala Wikipedia",
    },
    ie: {
        code: "ie",
        language: "Interlingue",
        script: "Latn",
        name: "Interlingue Wikipedia",
    },
    wo: {
        code: "wo",
        language: "Wolof",
        script: "Latn",
        name: "Wolof Wikipedia",
    },
    tpi: {
        code: "tpi",
        language: "Tok Pisin",
        script: "Latn",
        name: "Tok Pisin Wikipedia",
    },
    ty: {
        code: "ty",
        language: "Tahitian",
        script: "Latn",
        name: "Tahitian Wikipedia",
    },
    crh: {
        code: "crh",
        language: "Crimean Tatar",
        script: "Latn",
        name: "Crimean Tatar Wikipedia",
    },
    jbo: {
        code: "jbo",
        language: "Lojban",
        script: "Latn",
        name: "Lojban Wikipedia",
    },
    ay: {
        code: "ay",
        language: "Aymara",
        script: "Latn",
        name: "Aymara Wikipedia",
    },
    zea: {
        code: "zea",
        language: "Zealandic",
        script: "Latn",
        name: "Zealandic Wikipedia",
    },
    eml: {
        code: "eml",
        language: "Emilian-Romagnol",
        script: "Latn",
        name: "Emilian-Romagnol Wikipedia",
    },
    ky: {
        code: "ky",
        language: "Kyrgyz",
        script: "Cyrl",
        name: "Kyrgyz Wikipedia",
    },
    ig: {
        code: "ig",
        language: "Igbo",
        script: "Latn",
        name: "Igbo Wikipedia",
    },
    or: {
        code: "or",
        language: "Oriya",
        script: "Orya",
        name: "Oriya Wikipedia",
    },
    mg: {
        code: "mg",
        language: "Malagasy",
        script: "Latn",
        name: "Malagasy Wikipedia",
    },
    "cbk-zam": {
        code: "cbk-zam",
        language: "Zamboanga Chavacano",
        script: "Latn",
        name: "Zamboanga Chavacano Wikipedia",
    },
    kg: {
        code: "kg",
        language: "Kongo",
        script: "Latn",
        name: "Kongo Wikipedia",
    },
    arc: {
        code: "arc",
        language: "Syriac",
        script: "Syrc",
        name: "Syriac Wikipedia",
    },
    rmy: {
        code: "rmy",
        language: "Vlax Romani",
        script: "Latn/Deva",
        name: "Vlax Romani Wikipedia",
    },
    gn: {
        code: "gn",
        language: "Guarani",
        script: "Latn",
        name: "Guarani Wikipedia",
    },
    "mo (closed)": {
        code: "mo (closed)",
        language: "Moldovan",
        script: "Cyrl",
        name: "Moldovan Wikipedia",
    },
    so: {
        code: "so",
        language: "Somali",
        script: "Latn",
        name: "Somali Wikipedia",
    },
    kab: {
        code: "kab",
        language: "Kabyle",
        script: "Latn",
        name: "Kabyle Wikipedia",
    },
    ks: {
        code: "ks",
        language: "Kashmiri",
        script: "Arab/Deva",
        name: "Kashmiri Wikipedia",
    },
    stq: {
        code: "stq",
        language: "Saterland Frisian",
        script: "Latn",
        name: "Saterland Frisian Wikipedia",
    },
    ce: {
        code: "ce",
        language: "Chechen",
        script: "Cyrl",
        name: "Chechen Wikipedia",
    },
    udm: {
        code: "udm",
        language: "Udmurt",
        script: "Cyrl",
        name: "Udmurt Wikipedia",
    },
    mzn: {
        code: "mzn",
        language: "Mazandarani",
        script: "Perso",
        name: "Mazandarani Wikipedia",
    },
    pap: {
        code: "pap",
        language: "Papiamentu",
        script: "Latn",
        name: "Papiamentu Wikipedia",
    },
    cu: {
        code: "cu",
        language: "Old Church Slavonic",
        script: "Cyrs",
        name: "Old Church Slavonic Wikipedia",
    },
    sah: {
        code: "sah",
        language: "Sakha",
        script: "Cyrl",
        name: "Sakha Wikipedia",
    },
    tet: {
        code: "tet",
        language: "Tetum",
        script: "Latn",
        name: "Tetum Wikipedia",
    },
    sd: {
        code: "sd",
        language: "Sindhi",
        script: "Arab",
        name: "Sindhi Wikipedia",
    },
    lo: {
        code: "lo",
        language: "Lao",
        script: "Laoo",
        name: "Lao Wikipedia",
    },
    ba: {
        code: "ba",
        language: "Bashkir",
        script: "Cyrl",
        name: "Bashkir Wikipedia",
    },
    pnb: {
        code: "pnb",
        language: "Punjabi",
        script: "Shahmukhi",
        name: "Western Punjabi Wikipedia",
    },
    iu: {
        code: "iu",
        language: "Inuktitut",
        script: "Cans/Latn",
        name: "Iniktitut Wikipedia",
    },
    na: {
        code: "na",
        language: "Nauruan",
        script: "Latn",
        name: "Nauruan Wikipedia",
    },
    got: {
        code: "got",
        language: "Gothic",
        script: "Goth",
        name: "Gothic Wikipedia",
    },
    bo: {
        code: "bo",
        language: "Tibetan",
        script: "Tibt",
        name: "Tibetan Wikipedia",
    },
    dsb: {
        code: "dsb",
        language: "Lower Sorbian",
        script: "Latn",
        name: "Lower Sorbian Wikipedia",
    },
    chr: {
        code: "chr",
        language: "Cherokee",
        script: "Cher",
        name: "Cherokee Wikipedia",
    },
    cdo: {
        code: "cdo",
        language: "Min Dong",
        script: "Latn",
        name: "Min Dong Wikipedia",
    },
    hak: {
        code: "hak",
        language: "Hakka",
        script: "Latn",
        name: "Hakka Wikipedia",
    },
    om: {
        code: "om",
        language: "Oromo",
        script: "Latn",
        name: "Oromo Wikipedia",
    },
    my: {
        code: "my",
        language: "Burmese",
        script: "Mymr",
        name: "Burmese Wikipedia",
    },
    sm: {
        code: "sm",
        language: "Samoan",
        script: "Latn",
        name: "Samoan Wikipedia",
    },
    ee: {
        code: "ee",
        language: "Ewe",
        script: "Latn",
        name: "Ewe Wikipedia",
    },
    pcd: {
        code: "pcd",
        language: "Picard",
        script: "Latn",
        name: "Picard Wikipedia",
    },
    ug: {
        code: "ug",
        language: "Uyghur",
        script: "Latn/Arab",
        name: "Uyghur Wikipedia",
    },
    as: {
        code: "as",
        language: "Assamese",
        script: "Beng",
        name: "Assamese Wikipedia",
    },
    ti: {
        code: "ti",
        language: "Tigrinya",
        script: "Ethi",
        name: "Tigrinya Wikipedia",
    },
    av: {
        code: "av",
        language: "Avar",
        script: "Cyrl",
        name: "Avar Wikipedia",
    },
    bm: {
        code: "bm",
        language: "Bambara",
        script: "Latn",
        name: "Bambara Wikipedia",
    },
    zu: {
        code: "zu",
        language: "Zulu",
        script: "Latn",
        name: "Zulu Wikipedia",
    },
    pnt: {
        code: "pnt",
        language: "Pontic",
        script: "Grek",
        name: "Pontic Wikipedia",
    },
    nv: {
        code: "nv",
        language: "Navajo",
        script: "Latn",
        name: "Navajo Wikipedia",
    },
    cr: {
        code: "cr",
        language: "Cree",
        script: "Cans/Latn",
        name: "Cree Wikipedia",
    },
    pih: {
        code: "pih",
        language: "Norfolk",
        script: "Latn",
        name: "Norfolk Wikipedia",
    },
    ss: {
        code: "ss",
        language: "Swati",
        script: "Latn",
        name: "Swati Wikipedia",
    },
    ve: {
        code: "ve",
        language: "Venda",
        script: "Latn",
        name: "Venda Wikipedia",
    },
    bi: {
        code: "bi",
        language: "Bislama",
        script: "Latn",
        name: "Bislama Wikipedia",
    },
    rw: {
        code: "rw",
        language: "Kinyarwanda",
        script: "Latn",
        name: "Kinyarwanda Wikipedia",
    },
    ch: {
        code: "ch",
        language: "Chamorro",
        script: "Latn",
        name: "Chamorro Wikipedia",
    },
    arz: {
        code: "arz",
        language: "Egyptian Arabic",
        script: "Arab/Latn",
        name: "Egyptian Arabic Wikipedia",
    },
    xh: {
        code: "xh",
        language: "Xhosa",
        script: "Latn",
        name: "Xhosa Wikipedia",
    },
    kl: {
        code: "kl",
        language: "Greenlandic",
        script: "Latn",
        name: "Greenlandic Wikipedia",
    },
    ik: {
        code: "ik",
        language: "Inupiak",
        script: "Latn",
        name: "Inupiak Wikipedia",
    },
    bug: {
        code: "bug",
        language: "Buginese",
        script: "Bugi",
        name: "Buginese Wikipedia",
    },
    dz: {
        code: "dz",
        language: "Dzongkha",
        script: "Tibt",
        name: "Dzongkha Wikipedia",
    },
    ts: {
        code: "ts",
        language: "Tsonga",
        script: "Latn",
        name: "Tsonga Wikipedia",
    },
    tn: {
        code: "tn",
        language: "Tswana",
        script: "Latn",
        name: "Tswana Wikipedia",
    },
    kv: {
        code: "kv",
        language: "Komi",
        script: "Cyrl",
        name: "Komi Wikipedia",
    },
    tum: {
        code: "tum",
        language: "Tumbuka",
        script: "Latn",
        name: "Tumbuku Wikipedia",
    },
    xal: {
        code: "xal",
        language: "Kalmyk",
        script: "Cyrl",
        name: "Kalmyk Wikipedia",
    },
    st: {
        code: "st",
        language: "Sesotho",
        script: "Latn",
        name: "Sesotho Wikipedia",
    },
    tw: {
        code: "tw",
        language: "Twi",
        script: "Latn",
        name: "Twi Wikipedia",
    },
    bxr: {
        code: "bxr",
        language: "Buryat (Russia)",
        script: "Cyrl",
        name: "Buryat (Russia) Wikipedia",
    },
    ak: {
        code: "ak",
        language: "Akan",
        script: "Latn",
        name: "Akan Wikipedia",
    },
    ab: {
        code: "ab",
        language: "Abkhazian",
        script: "Cyrl",
        name: "Abkhazian Wikipedia",
    },
    ny: {
        code: "ny",
        language: "Chichewa",
        script: "Latn",
        name: "Chichewa Wikipedia",
    },
    fj: {
        code: "fj",
        language: "Fijian",
        script: "Latn",
        name: "Fijian Wikipedia",
    },
    lbe: {
        code: "lbe",
        language: "Lak",
        script: "Cyrl",
        name: "Lak Wikipedia",
    },
    ki: {
        code: "ki",
        language: "Kikuyu",
        script: "Latn",
        name: "Kikuyu Wikipedia",
    },
    za: {
        code: "za",
        language: "Zhuang",
        script: "Latn",
        name: "Zhuang Wikipedia",
    },
    ff: {
        code: "ff",
        language: "Fula",
        script: "Latn",
        name: "Fula Wikipedia",
    },
    lg: {
        code: "lg",
        language: "Luganda",
        script: "Latn",
        name: "Luganda Wikipedia",
    },
    sn: {
        code: "sn",
        language: "Shona",
        script: "Latn",
        name: "Shona Wikipedia",
    },
    ha: {
        code: "ha",
        language: "Hausa",
        script: "Latn",
        name: "Hausa Wikipedia",
    },
    sg: {
        code: "sg",
        language: "Sango",
        script: "Latn",
        name: "Sango Wikipedia",
    },
    ii: {
        code: "ii",
        language: "Sichuan Yi",
        script: "Yiii",
        name: "Sichuan Yi Wikipedia",
    },
    cho: {
        code: "cho",
        language: "Choctaw",
        script: "Latn",
        name: "Choctaw Wikipedia",
    },
    rn: {
        code: "rn",
        language: "Kirundi",
        script: "Latn",
        name: "Kirundi Wikipedia",
    },
    mh: {
        code: "mh",
        language: "Marshallese",
        script: "Latn",
        name: "Marshallese Wikipedia",
    },
    chy: {
        code: "chy",
        language: "Cheyenne",
        script: "Latn",
        name: "Cheyenne Wikipedia",
    },
    ng: {
        code: "ng",
        language: "Ndonga",
        script: "Latn",
        name: "Ndonga Wikipedia",
    },
    kj: {
        code: "kj",
        language: "Kuanyama",
        script: "Latn",
        name: "Kuanyama Wikipedia",
    },
    ho: {
        code: "ho",
        language: "Hiri Motu",
        script: "Latn",
        name: "Hiri Motu Wikipedia",
    },
    mus: {
        code: "mus",
        language: "Muscogee",
        script: "Latn",
        name: "Muscogee Wikipedia",
    },
    kr: {
        code: "kr",
        language: "Kanuri",
        script: "Latn",
        name: "Kanuri Wikipedia",
    },
    hz: {
        code: "hz",
        language: "Herero",
        script: "Latn",
        name: "Herero Wikipedia",
    },
    mwl: {
        code: "mwl",
        language: "Moloko",
        script: "Latn",
        name: "Moloko Wikipedia",
    },
    pa: {
        code: "pa",
        language: "Punjabi",
        script: "Guru",
        name: "Punjabi Wikipedia",
    },
    xmf: {
        code: "xmf",
        language: "Mingrelian",
        script: "Geor",
        name: "Mingrelian Wikipedia",
    },
    lez: {
        code: "lez",
        language: "Lezgian",
        script: "Cyrl",
        name: "Lezgi Wikipedia",
    },
    chm: {
        code: "chm",
        language: "Champenoisian",
        script: "Latn",
        name: "Champenois Wikipedia",
    },
} as const;
